### ISSUE TITLE
error: cannot find 'PangoLanguageUnsafeMutablePointer' in scope

### ISSUE THREAD

**Issue by jasaldivara** [rhx/SwiftPango#3]
I'm trying to build a SwiftGtk (Gtk 3) based project on Fedora 37 x86_64, but i'm getting this error message:

```
.build/plugins/outputs/swiftpango/Pango/gir2swift-plugin/gir2swift-generated/Pango/Pango-1.0-L.swift:2141:29: error: cannot find 'PangoLanguageUnsafeMutablePointer' in scope
            return rv.map { PangoLanguageUnsafeMutablePointer<PangoLanguage>($0) }
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Also, I'm seeing a lot of these messages, not sure if they are related to the error:

```
<unknown>:0: remark: unable to perform implicit import of "_StringProcessing" module: no such module found
<unknown>:0: remark: unable to perform implicit import of "_StringProcessing" module: no such module found
<unknown>:0: remark: unable to perform implicit import of "_StringProcessing" module: no such module found
<unknown>:0: remark: unable to perform implicit import of "_StringProcessing" module: no such module found
```

**Comment by rhx** [comment]
The `PangoLanguageUnsafeMutablePointer` issue appears to be the bug that was fixed with the latest commit.  Could you try the following (in your `SwiftPango` folder) and see if this fixes the problem?
```Shell
git checkout main
git pull
./distclean.sh
swift package purge-cache
swift build
```

The `_StringProcessing` issue is a separate Swift compiler/library issue that pops up on some versions of Linux and Swift (but has nothing to with SwiftPango).

**Comment by rhx** [comment]
The above steps should also work in the `SwiftGtk` directory (but will take longer, of course, as it compiles plenty of other packages as well).

**Comment by jasaldivara** [comment]
If I run these commands inside `.build/checkouts/SwiftPango`, and then `swift build` in the root directory of my package, the error message is still present.

But if I delete the `.build/plugins/outputs/swiftpango` (after running the commands), the problem is fixed, and my package is built without problems.

There is something strange: If I delete the `.build ` directory of my package, and then run `swift build`, the error message is still present. If I go to  `.build/checkouts/SwiftPango`, the git HEAD is detached and pointing to commit `3278215`. This is one commit before the one pointed by the `main` branch.

But then I found the solution: I just deleted the `Package.resolved` file along with the `.build` directory inside my package, and then the error message is no longer there.
